--data for lecturer
insert into lecturer (first_name, last_name, experience) values ('Ab', 'Ridings', 3);
insert into lecturer (first_name, last_name, experience) values ('Ezri', 'Tittershill', 22);
insert into lecturer (first_name, last_name, experience) values ('Meghan', 'Raynor', 5);
insert into lecturer (first_name, last_name, experience) values ('Goldia', 'Kalinsky', 27);
insert into lecturer (first_name, last_name, experience) values ('Vail', 'Bassill', 17);
insert into lecturer (first_name, last_name, experience) values ('Lynne', 'McVaugh', 0);
insert into lecturer (first_name, last_name, experience) values ('Skyler', 'Pickersail', 21);
insert into lecturer (first_name, last_name, experience) values ('Flossie', 'Kliemchen', 18);
insert into lecturer (first_name, last_name, experience) values ('Jasmin', 'Kirman', 11);
insert into lecturer (first_name, last_name, experience) values ('Addie', 'Haythorn', 2);
insert into lecturer (first_name, last_name, experience) values ('Nickey', 'Spriggs', 2);
insert into lecturer (first_name, last_name, experience) values ('Clim', 'Hare', 4);
insert into lecturer (first_name, last_name, experience) values ('Mickie', 'Bloxham', 26);
insert into lecturer (first_name, last_name, experience) values ('Gaby', 'Maken', 6);
insert into lecturer (first_name, last_name, experience) values ('Shadow', 'Ainsby', 7);
insert into lecturer (first_name, last_name, experience) values ('Ruttger', 'Halfacre', 12);
insert into lecturer (first_name, last_name, experience) values ('Linus', 'Cuseick', 30);
insert into lecturer (first_name, last_name, experience) values ('Margie', 'Filasov', 1);
insert into lecturer (first_name, last_name, experience) values ('Rich', 'Cristofori', 17);
insert into lecturer (first_name, last_name, experience) values ('Tremain', 'de Clercq', 9);
insert into lecturer (first_name, last_name, experience) values ('Reyna', 'Alekseicik', 0);
insert into lecturer (first_name, last_name, experience) values ('Britney', 'Fishlee', 26);
insert into lecturer (first_name, last_name, experience) values ('Minni', 'Davydychev', 5);
insert into lecturer (first_name, last_name, experience) values ('Beret', 'Melan', 10);
insert into lecturer (first_name, last_name, experience) values ('Beverley', 'Soars', 26);
insert into lecturer (first_name, last_name, experience) values ('Stillman', 'Josskoviz', 0);
insert into lecturer (first_name, last_name, experience) values ('Karoline', 'Pien', 21);
insert into lecturer (first_name, last_name, experience) values ('Lian', 'Tomasutti', 28);
insert into lecturer (first_name, last_name, experience) values ('Lucio', 'Frogley', 30);
insert into lecturer (first_name, last_name, experience) values ('Tracy', 'Baybutt', 22);
insert into lecturer (first_name, last_name, experience) values ('Fonz', 'Cresar', 29);
insert into lecturer (first_name, last_name, experience) values ('Anallise', 'Mandel', 28);
insert into lecturer (first_name, last_name, experience) values ('Ardis', 'Marzello', 10);
insert into lecturer (first_name, last_name, experience) values ('Sylvan', 'Stickland', 18);
insert into lecturer (first_name, last_name, experience) values ('Garey', 'Newing', 23);
insert into lecturer (first_name, last_name, experience) values ('Melosa', 'Purches', 23);
insert into lecturer (first_name, last_name, experience) values ('Shani', 'Langtree', 9);
insert into lecturer (first_name, last_name, experience) values ('Dominic', 'Mallender', 3);
insert into lecturer (first_name, last_name, experience) values ('Othello', 'Melato', 26);
insert into lecturer (first_name, last_name, experience) values ('Gerty', 'Wickling', 9);
insert into lecturer (first_name, last_name, experience) values ('Pepito', 'Tremayle', 15);
insert into lecturer (first_name, last_name, experience) values ('Melloney', 'Baine', 26);
insert into lecturer (first_name, last_name, experience) values ('Averell', 'McCaughan', 5);
insert into lecturer (first_name, last_name, experience) values ('Todd', 'Kays', 20);
insert into lecturer (first_name, last_name, experience) values ('Lek', 'Scurrah', 9);
insert into lecturer (first_name, last_name, experience) values ('Marleen', 'Miche', 3);
insert into lecturer (first_name, last_name, experience) values ('Chaddie', 'Cherry', 17);
insert into lecturer (first_name, last_name, experience) values ('Dolf', 'Crush', 12);
insert into lecturer (first_name, last_name, experience) values ('Stacee', 'Hasty', 25);
insert into lecturer (first_name, last_name, experience) values ('Gusty', 'Brahmer', 28);

--data for student
insert into student (first_name, last_name, numGroup) values ('Erich', 'Cornelleau', '11-002');
insert into student (first_name, last_name, numGroup) values ('Lenore', 'Ferretti', '11-002');
insert into student (first_name, last_name, numGroup) values ('Drucill', 'McWilliam', '11-001');
insert into student (first_name, last_name, numGroup) values ('Langston', 'Credland', '10-903');
insert into student (first_name, last_name, numGroup) values ('Klemens', 'Ventam', '12-103');
insert into student (first_name, last_name, numGroup) values ('Lynda', 'Gerty', '11-001');
insert into student (first_name, last_name, numGroup) values ('Tybi', 'Baudon', '11-001');
insert into student (first_name, last_name, numGroup) values ('My', 'Hardesty', '10-903');
insert into student (first_name, last_name, numGroup) values ('Jillian', 'Wheelan', '11-003');
insert into student (first_name, last_name, numGroup) values ('Frieda', 'Wyrall', '11-002');
insert into student (first_name, last_name, numGroup) values ('Kaye', 'Ashmore', '10-903');
insert into student (first_name, last_name, numGroup) values ('Florentia', 'Kelf', '11-001');
insert into student (first_name, last_name, numGroup) values ('Bryanty', 'Shwalbe', '11-002');
insert into student (first_name, last_name, numGroup) values ('Rod', 'Lamplough', '11-002');
insert into student (first_name, last_name, numGroup) values ('Rosella', 'Rundall', '11-002');
insert into student (first_name, last_name, numGroup) values ('Andrea', 'McParland', '11-002');
insert into student (first_name, last_name, numGroup) values ('Margarete', 'Jenson', '11-002');
insert into student (first_name, last_name, numGroup) values ('Valentina', 'Hayfield', '11-002');
insert into student (first_name, last_name, numGroup) values ('Chad', 'Beardshaw', '11-002');
insert into student (first_name, last_name, numGroup) values ('Vittoria', 'Yardy', '11-002');
insert into student (first_name, last_name, numGroup) values ('Christal', 'McQuillin', '11-001');
insert into student (first_name, last_name, numGroup) values ('Raphaela', 'Haddeston', '11-001');
insert into student (first_name, last_name, numGroup) values ('Ynez', 'Tranmer', '11-001');
insert into student (first_name, last_name, numGroup) values ('Henrietta', 'Josofovitz', '10-903');
insert into student (first_name, last_name, numGroup) values ('Crysta', 'Toopin', '10-903');
insert into student (first_name, last_name, numGroup) values ('Danette', 'Carus', '10-903');
insert into student (first_name, last_name, numGroup) values ('Sophey', 'Buglar', '10-903');
insert into student (first_name, last_name, numGroup) values ('Grant', 'Cheng', '10-903');
insert into student (first_name, last_name, numGroup) values ('Binky', 'Howsam', '12-103');
insert into student (first_name, last_name, numGroup) values ('Mel', 'Lesaunier', '12-103');
insert into student (first_name, last_name, numGroup) values ('Garnet', 'Steljes', '12-103');
insert into student (first_name, last_name, numGroup) values ('Adrea', 'Melmore', '12-103');
insert into student (first_name, last_name, numGroup) values ('Darlleen', 'McGhie', '12-103');
insert into student (first_name, last_name, numGroup) values ('Edwin', 'Sterte', '11-002');
insert into student (first_name, last_name, numGroup) values ('Gail', 'Drogan', '11-001');
insert into student (first_name, last_name, numGroup) values ('Mariska', 'Hobbema', '12-103');
insert into student (first_name, last_name, numGroup) values ('Zelda', 'Gregoli', '10-903');
insert into student (first_name, last_name, numGroup) values ('Nat', 'Blamphin', '11-003');
insert into student (first_name, last_name, numGroup) values ('Rupert', 'McNeil', '11-003');
insert into student (first_name, last_name, numGroup) values ('Freeman', 'Ruppelin', '11-003');
insert into student (first_name, last_name, numGroup) values ('Mechelle', 'Farryan', '11-003');
insert into student (first_name, last_name, numGroup) values ('Reggie', 'Kramer', '11-003');
insert into student (first_name, last_name, numGroup) values ('Clyde', 'Haddick', '11-001');
insert into student (first_name, last_name, numGroup) values ('Renie', 'Moutray Read', '11-002');
insert into student (first_name, last_name, numGroup) values ('Quinta', 'Stoke', '11-003');
insert into student (first_name, last_name, numGroup) values ('Arnuad', 'Moule', '11-003');
insert into student (first_name, last_name, numGroup) values ('Zackariah', 'MacLucais', '11-001');
insert into student (first_name, last_name, numGroup) values ('Donica', 'Lots', '11-002');
insert into student (first_name, last_name, numGroup) values ('Vance', 'Lyons', '10-903');
insert into student (first_name, last_name, numGroup) values ('Carlie', 'Siderfin', '12-103');

--data for course
insert into course (name, start_end_date, lecturer_id) values ('Algebra', '04.09.2021/05.01.2022', 17);
insert into course (name, start_end_date, lecturer_id) values ('Programming', '12.09.2021/05.02.2022', 50);
insert into course (name, start_end_date, lecturer_id) values ('History', '14.09.2021/15.03.2022', 48);
insert into course (name, start_end_date, lecturer_id) values ('Psychology', '01.09.2021/25.04.2022', 1);
insert into course (name, start_end_date, lecturer_id) values ('Algorithms', '19.09.2021/05.05.2022', 12);
insert into course (name, start_end_date, lecturer_id) values ('Math', '19.12.2021/05.06.2022', 42);
insert into course (name, start_end_date, lecturer_id) values ('Russian', '13.10.2021/03.04.2022', 23);
insert into course (name, start_end_date, lecturer_id) values ('English', '14.09.2021/15.01.2022', 34);
insert into course (name, start_end_date, lecturer_id) values ('Machine learning', '04.10.2021/05.02.2022', 21);
insert into course (name, start_end_date, lecturer_id) values ('Mechanic', '03.09.2021/05.01.2022', 12);

--data for student_course
insert into student_course (id_student, id_course) values (2, 5);
insert into student_course (id_student, id_course) values (39, 8);
insert into student_course (id_student, id_course) values (48, 5);
insert into student_course (id_student, id_course) values (34, 1);
insert into student_course (id_student, id_course) values (19, 5);
insert into student_course (id_student, id_course) values (26, 6);
insert into student_course (id_student, id_course) values (21, 9);
insert into student_course (id_student, id_course) values (27, 7);
insert into student_course (id_student, id_course) values (21, 8);
insert into student_course (id_student, id_course) values (12, 1);
insert into student_course (id_student, id_course) values (30, 7);
insert into student_course (id_student, id_course) values (29, 3);
insert into student_course (id_student, id_course) values (20, 1);
insert into student_course (id_student, id_course) values (33, 1);
insert into student_course (id_student, id_course) values (6, 9);
insert into student_course (id_student, id_course) values (3, 1);
insert into student_course (id_student, id_course) values (33, 8);
insert into student_course (id_student, id_course) values (42, 8);
insert into student_course (id_student, id_course) values (30, 2);
insert into student_course (id_student, id_course) values (14, 7);
insert into student_course (id_student, id_course) values (12, 4);
insert into student_course (id_student, id_course) values (1, 1);
insert into student_course (id_student, id_course) values (40, 5);
insert into student_course (id_student, id_course) values (32, 1);
insert into student_course (id_student, id_course) values (38, 10);
insert into student_course (id_student, id_course) values (4, 6);
insert into student_course (id_student, id_course) values (40, 9);
insert into student_course (id_student, id_course) values (13, 9);
insert into student_course (id_student, id_course) values (18, 1);
insert into student_course (id_student, id_course) values (7, 8);
insert into student_course (id_student, id_course) values (49, 10);
insert into student_course (id_student, id_course) values (7, 8);
insert into student_course (id_student, id_course) values (13, 10);
insert into student_course (id_student, id_course) values (41, 3);
insert into student_course (id_student, id_course) values (4, 2);
insert into student_course (id_student, id_course) values (4, 4);
insert into student_course (id_student, id_course) values (7, 2);
insert into student_course (id_student, id_course) values (43, 8);
insert into student_course (id_student, id_course) values (40, 1);
insert into student_course (id_student, id_course) values (27, 9);
insert into student_course (id_student, id_course) values (3, 8);
insert into student_course (id_student, id_course) values (44, 6);
insert into student_course (id_student, id_course) values (24, 1);
insert into student_course (id_student, id_course) values (40, 1);
insert into student_course (id_student, id_course) values (36, 1);
insert into student_course (id_student, id_course) values (28, 3);
insert into student_course (id_student, id_course) values (10, 5);
insert into student_course (id_student, id_course) values (21, 5);
insert into student_course (id_student, id_course) values (8, 6);
insert into student_course (id_student, id_course) values (26, 6);
insert into student_course (id_student, id_course) values (26, 10);
insert into student_course (id_student, id_course) values (44, 2);
insert into student_course (id_student, id_course) values (25, 9);
insert into student_course (id_student, id_course) values (33, 4);
insert into student_course (id_student, id_course) values (10, 5);
insert into student_course (id_student, id_course) values (24, 2);
insert into student_course (id_student, id_course) values (6, 2);
insert into student_course (id_student, id_course) values (44, 5);
insert into student_course (id_student, id_course) values (6, 1);
insert into student_course (id_student, id_course) values (27, 5);
insert into student_course (id_student, id_course) values (17, 2);
insert into student_course (id_student, id_course) values (18, 7);
insert into student_course (id_student, id_course) values (4, 1);
insert into student_course (id_student, id_course) values (2, 9);
insert into student_course (id_student, id_course) values (12, 6);
insert into student_course (id_student, id_course) values (32, 7);
insert into student_course (id_student, id_course) values (13, 9);
insert into student_course (id_student, id_course) values (48, 6);
insert into student_course (id_student, id_course) values (18, 10);
insert into student_course (id_student, id_course) values (19, 8);
insert into student_course (id_student, id_course) values (3, 3);
insert into student_course (id_student, id_course) values (18, 7);
insert into student_course (id_student, id_course) values (29, 3);
insert into student_course (id_student, id_course) values (39, 4);
insert into student_course (id_student, id_course) values (29, 1);
insert into student_course (id_student, id_course) values (10, 6);
insert into student_course (id_student, id_course) values (50, 1);
insert into student_course (id_student, id_course) values (3, 7);
insert into student_course (id_student, id_course) values (23, 4);
insert into student_course (id_student, id_course) values (47, 9);
insert into student_course (id_student, id_course) values (22, 7);
insert into student_course (id_student, id_course) values (24, 10);
insert into student_course (id_student, id_course) values (36, 6);
insert into student_course (id_student, id_course) values (3, 2);
insert into student_course (id_student, id_course) values (12, 5);
insert into student_course (id_student, id_course) values (26, 7);
insert into student_course (id_student, id_course) values (9, 6);
insert into student_course (id_student, id_course) values (47, 2);
insert into student_course (id_student, id_course) values (20, 1);
insert into student_course (id_student, id_course) values (26, 10);
insert into student_course (id_student, id_course) values (6, 8);
insert into student_course (id_student, id_course) values (12, 9);
insert into student_course (id_student, id_course) values (43, 8);
insert into student_course (id_student, id_course) values (26, 10);
insert into student_course (id_student, id_course) values (38, 6);
insert into student_course (id_student, id_course) values (8, 2);
insert into student_course (id_student, id_course) values (7, 10);
insert into student_course (id_student, id_course) values (13, 4);
insert into student_course (id_student, id_course) values (15, 4);
insert into student_course (id_student, id_course) values (49, 5);

--data for lesson
insert into lesson(name, day_of_week, id_course) VALUES ('A','Monday/11:00',1);
insert into lesson(name, day_of_week, id_course) VALUES ('B','Tuesday/10:00',1);
insert into lesson(name, day_of_week, id_course) VALUES ('C','Wednesday/8:00',1);
insert into lesson(name, day_of_week, id_course) VALUES ('L','Saturday/11:00',2);
insert into lesson(name, day_of_week, id_course) VALUES ('PL','Friday/10:00',2);
insert into lesson(name, day_of_week, id_course) VALUES ('RT','Wednesday/8:00',2);
insert into lesson(name, day_of_week, id_course) VALUES ('K','Saturday/11:00',3);
insert into lesson(name, day_of_week, id_course) VALUES ('KL','Friday/10:00',3);
insert into lesson(name, day_of_week, id_course) VALUES ('NT','Wednesday/8:00',3);
insert into lesson(name, day_of_week, id_course) VALUES ('PP','Monday/11:00',4);
insert into lesson(name, day_of_week, id_course) VALUES ('AA','Thursday/11:00',4);
insert into lesson(name, day_of_week, id_course) VALUES ('CC','Wednesday/12:00',4);
insert into lesson(name, day_of_week, id_course) VALUES ('L','Saturday/11:00',5);
insert into lesson(name, day_of_week, id_course) VALUES ('PL','Friday/10:00',5);
insert into lesson(name, day_of_week, id_course) VALUES ('PO','Wednesday/8:00',5);
insert into lesson(name, day_of_week, id_course) VALUES ('LL','Saturday/11:00',6);
insert into lesson(name, day_of_week, id_course) VALUES ('OP','Friday/10:00',6);
insert into lesson(name, day_of_week, id_course) VALUES ('MA','Wednesday/8:00',6);
insert into lesson(name, day_of_week, id_course) VALUES ('RR','Monday/11:00',7);
insert into lesson(name, day_of_week, id_course) VALUES ('OO','Tuesday/10:00',7);
insert into lesson(name, day_of_week, id_course) VALUES ('QQ','Wednesday/8:00',7);
insert into lesson(name, day_of_week, id_course) VALUES ('LQ','Saturday/11:00',7);
insert into lesson(name, day_of_week, id_course) VALUES ('ON','Friday/10:00',8);
insert into lesson(name, day_of_week, id_course) VALUES ('OP','Wednesday/8:00',8);
insert into lesson(name, day_of_week, id_course) VALUES ('QWE','Saturday/11:00',9);
insert into lesson(name, day_of_week, id_course) VALUES ('NNN','Friday/10:00',9);
insert into lesson(name, day_of_week, id_course) VALUES ('NP','Saturday/8:00',10);